# Generated by Django 3.1.5 on 2021-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.IntegerField(default=None)),
                ('tdate', models.IntegerField(default=None)),
                ('tmonth', models.IntegerField(default=None)),
                ('tyear', models.IntegerField(default=None)),
            ],
        ),
    ]
