# Generated by Django 3.1.5 on 2021-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_newsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='totalPrice',
            field=models.IntegerField(default=None),
        ),
    ]
